### ISSUE TITLE
Sam Final Review Ticket

### ISSUE THREAD

**Issue by dsblack0** [dsblack0/stickers_for_charity#56]
# 3 Weeks Plans
**Week 1**
- [x] Finish frontend HTML for ["About Team"](https://github.com/dsblack0/stickers_for_charity/issues/12) page(s)
- [x] Finish frontend HTML for ["Login Page"](https://github.com/dsblack0/stickers_for_charity/issues/20)
- [x] Add about team information provided by club

**Week 2**
- [ ]  Add authentication and authorization for admins to edit any page with dynamic info (about team, regulating reviews, regulating sticker orders) and club members to have access to add own sticker designs to order page
     - going off of Prisha's database

**Week 3**
- [ ] Finishing database to save anything inputted by users on the "About Team" page

# Week 1 Progress
**About Team Page**
- [Issue](https://github.com/dsblack0/stickers_for_charity/issues/12)
- [HTML](https://github.com/dsblack0/stickers_for_charity/blob/master/src/main/resources/templates/aboutTeam.html) & [Java](https://github.com/dsblack0/stickers_for_charity/blob/master/src/main/java/com/example/sping_portfolio/controllers/aboutTeam.java) code
- Current State of page:
![image](https://user-images.githubusercontent.com/70492417/168303658-b4ad2492-8d72-42fd-a8d1-600f79ec2eef.png)
![image](https://user-images.githubusercontent.com/70492417/168303816-8e79f79a-54e3-494a-ab6e-1d3357c07c20.png)

# Final Grading

### Meeting Tech Guidelines (20 pts)
- [ ] Individual Assignment and Completion: ["About Team"](https://github.com/dsblack0/stickers_for_charity/issues/12) & ["Login Page"](https://github.com/dsblack0/stickers_for_charity/issues/20)
- [x] Requirement Verified and Accepted by Sponsor: President of the club agreed to the requirements in [presentation](https://docs.google.com/presentation/d/1bJK0mjS-OzZ1H4lfNiHI4ZFaRIz9ZaQ5aZCExAhJdbE/edit?usp=sharing)
- [ ] Presentation at N@TM
- [ ] Presentation/Requirements Verified by Mr. M

### Meeting New Tech Achievements (5 pts)
- [ ] Database w/ Multiple Tables
- [ ] Authentication of Authorization Controls
- [ ] Meaningful Capture

### Teacher Interpretation (5 pts)
- Individual Work
- Team Work
