### ISSUE TITLE
Team Final Dev 1 Review Ticket

### ISSUE THREAD

**Issue by dsblack0** [dsblack0/stickers_for_charity#61]
## Week 1 (5/11 - 5/18)
- [x] Week 2 Review 2 on 5/13 --> Progress should be shown on this Weeks tasks

### Kaavya
- [Review Ticket](https://github.com/dsblack0/stickers_for_charity/issues/59) w/ tangibles for progress
- [x] Finish [Frontend HTML](https://github.com/dsblack0/stickers_for_charity/commit/d39dcea9782a64076641716f9a94964aaa8adadb) for Custom Stickers Page [(Review Ticket)](https://github.com/dsblack0/stickers_for_charity/issues/16)
- [x] Create form for Meaningful Capture

### Prisha
- [ ] Sign-up database (newly created accounts through the sign-up page will be added to the table)

### Maggie
- [Review Ticket](https://github.com/dsblack0/stickers_for_charity/issues/60) w/ tangibles for progress
- [x] Try to get the general site font working through the CSS files
- [x] Create and finish frontend HTML for the "reviews" page
- [x] create "events" page controller
- [x] add club information on "home" page provided by club

### Sam
- [Review Ticket](https://github.com/dsblack0/stickers_for_charity/issues/58) w/ tangibles for progress
- [x] Finish frontend HTML for ["About Team"](https://github.com/dsblack0/stickers_for_charity/issues/12) page(s)
- [x] Finish frontend HTML for ["Login Page"](https://github.com/dsblack0/stickers_for_charity/issues/20)
- [x] Add about team information provided by club

### Chenxin
- [Review Ticket](https://github.com/dsblack0/stickers_for_charity/issues/57) w/ tangibles for progress
 - [ ] Deploy project with AWS

**Comment by wrachel** [comment]
Crossover Team Review:

## Overall team score: 0.9/1 (maximum you can get according to requirements)
* Overall team is making progress towards finishing their project on time 
* Each person has thorough work that contributes to the team
* no person is working on "random" code 

##Individual Scores:
Kaavya: 0.9/1
*

**Comment by KaavyaU** [comment]
## Feedback from Sub
- Develop more in the backend
- Liked the frontend and design of the webpage
- Liked the choice in sponsor --> Liked the idea of using art for charitable organizations
